name: Continuous Integration
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  build-summary:
    name: Build Summary Image
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Git pull
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: requirements-${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install wkhtmltopdf
        run: sudo apt-get install xvfb libfontconfig wkhtmltopdf
      - name: Create summary PNG
        run: python -m aoc.scripts.image_summary
        env:
          AOC_SESSION: ${{ secrets.AOC_SESSION }}
      - name: Push summary PNG updates
        run: |
          git config --global user.name 'GitHub CI'
          git config --global user.email 'github.ci@github.com'
          git add aoc/summary.jpg
          git diff-index --quiet HEAD || (git commit -m "[Automated] summary PNG update" && git push)
